# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-12.app/Contents/bin/cmake" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-12.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/michaelbao/Code/ogf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/michaelbao/Code/ogf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-12.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	"/Applications/CMake 2.8-12.app/Contents/bin/ctest" --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelbao/Code/ogf/CMakeFiles /Users/michaelbao/Code/ogf/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/michaelbao/Code/ogf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Core

# Build rule for target.
Core: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Core
.PHONY : Core

# fast build rule for target.
Core/fast:
	$(MAKE) -f "Beta Framework/Core/CMakeFiles/Core.dir/build.make" "Beta Framework/Core/CMakeFiles/Core.dir/build"
.PHONY : Core/fast

#=============================================================================
# Target rules for targets named Gfx

# Build rule for target.
Gfx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Gfx
.PHONY : Gfx

# fast build rule for target.
Gfx/fast:
	$(MAKE) -f "Beta Framework/GfxRenderSubsystem/CMakeFiles/Gfx.dir/build.make" "Beta Framework/GfxRenderSubsystem/CMakeFiles/Gfx.dir/build"
.PHONY : Gfx/fast

#=============================================================================
# Target rules for targets named Audio

# Build rule for target.
Audio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Audio
.PHONY : Audio

# fast build rule for target.
Audio/fast:
	$(MAKE) -f "Beta Framework/AudioSubsystem/CMakeFiles/Audio.dir/build.make" "Beta Framework/AudioSubsystem/CMakeFiles/Audio.dir/build"
.PHONY : Audio/fast

#=============================================================================
# Target rules for targets named Network

# Build rule for target.
Network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Network
.PHONY : Network

# fast build rule for target.
Network/fast:
	$(MAKE) -f "Beta Framework/NetworkLibrary/CMakeFiles/Network.dir/build.make" "Beta Framework/NetworkLibrary/CMakeFiles/Network.dir/build"
.PHONY : Network/fast

#=============================================================================
# Target rules for targets named CORE-ConfigReadWriteTest

# Build rule for target.
CORE-ConfigReadWriteTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-ConfigReadWriteTest
.PHONY : CORE-ConfigReadWriteTest

# fast build rule for target.
CORE-ConfigReadWriteTest/fast:
	$(MAKE) -f "Delta Applications/Tests/CORE-ConfigReadWriteTest/CMakeFiles/CORE-ConfigReadWriteTest.dir/build.make" "Delta Applications/Tests/CORE-ConfigReadWriteTest/CMakeFiles/CORE-ConfigReadWriteTest.dir/build"
.PHONY : CORE-ConfigReadWriteTest/fast

#=============================================================================
# Target rules for targets named CORE-MessagingTest

# Build rule for target.
CORE-MessagingTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-MessagingTest
.PHONY : CORE-MessagingTest

# fast build rule for target.
CORE-MessagingTest/fast:
	$(MAKE) -f "Delta Applications/Tests/CORE-MessagingTest/CMakeFiles/CORE-MessagingTest.dir/build.make" "Delta Applications/Tests/CORE-MessagingTest/CMakeFiles/CORE-MessagingTest.dir/build"
.PHONY : CORE-MessagingTest/fast

#=============================================================================
# Target rules for targets named GFX-CameraMoveTest

# Build rule for target.
GFX-CameraMoveTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-CameraMoveTest
.PHONY : GFX-CameraMoveTest

# fast build rule for target.
GFX-CameraMoveTest/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-CameraMoveTest/CMakeFiles/GFX-CameraMoveTest.dir/build.make" "Delta Applications/Tests/GFX-CameraMoveTest/CMakeFiles/GFX-CameraMoveTest.dir/build"
.PHONY : GFX-CameraMoveTest/fast

#=============================================================================
# Target rules for targets named GFX-TextureTest

# Build rule for target.
GFX-TextureTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-TextureTest
.PHONY : GFX-TextureTest

# fast build rule for target.
GFX-TextureTest/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-TextureTest/CMakeFiles/GFX-TextureTest.dir/build.make" "Delta Applications/Tests/GFX-TextureTest/CMakeFiles/GFX-TextureTest.dir/build"
.PHONY : GFX-TextureTest/fast

#=============================================================================
# Target rules for targets named GfxRenderExample

# Build rule for target.
GfxRenderExample: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GfxRenderExample
.PHONY : GfxRenderExample

# fast build rule for target.
GfxRenderExample/fast:
	$(MAKE) -f "Delta Applications/Tests/GfxRenderExample/CMakeFiles/GfxRenderExample.dir/build.make" "Delta Applications/Tests/GfxRenderExample/CMakeFiles/GfxRenderExample.dir/build"
.PHONY : GfxRenderExample/fast

#=============================================================================
# Target rules for targets named GfxViewportTest

# Build rule for target.
GfxViewportTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GfxViewportTest
.PHONY : GfxViewportTest

# fast build rule for target.
GfxViewportTest/fast:
	$(MAKE) -f "Delta Applications/Tests/GfxViewportTest/CMakeFiles/GfxViewportTest.dir/build.make" "Delta Applications/Tests/GfxViewportTest/CMakeFiles/GfxViewportTest.dir/build"
.PHONY : GfxViewportTest/fast

#=============================================================================
# Target rules for targets named SDL-InputTest

# Build rule for target.
SDL-InputTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SDL-InputTest
.PHONY : SDL-InputTest

# fast build rule for target.
SDL-InputTest/fast:
	$(MAKE) -f "Delta Applications/Tests/SDL-InputTest/CMakeFiles/SDL-InputTest.dir/build.make" "Delta Applications/Tests/SDL-InputTest/CMakeFiles/SDL-InputTest.dir/build"
.PHONY : SDL-InputTest/fast

#=============================================================================
# Target rules for targets named GFX-Cube

# Build rule for target.
GFX-Cube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-Cube
.PHONY : GFX-Cube

# fast build rule for target.
GFX-Cube/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-Cube/CMakeFiles/GFX-Cube.dir/build.make" "Delta Applications/Tests/GFX-Cube/CMakeFiles/GFX-Cube.dir/build"
.PHONY : GFX-Cube/fast

#=============================================================================
# Target rules for targets named GFX-MultiCube

# Build rule for target.
GFX-MultiCube: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-MultiCube
.PHONY : GFX-MultiCube

# fast build rule for target.
GFX-MultiCube/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-MultiCube/CMakeFiles/GFX-MultiCube.dir/build.make" "Delta Applications/Tests/GFX-MultiCube/CMakeFiles/GFX-MultiCube.dir/build"
.PHONY : GFX-MultiCube/fast

#=============================================================================
# Target rules for targets named GFX-MultiCubeTex

# Build rule for target.
GFX-MultiCubeTex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-MultiCubeTex
.PHONY : GFX-MultiCubeTex

# fast build rule for target.
GFX-MultiCubeTex/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-MultiCubeTex/CMakeFiles/GFX-MultiCubeTex.dir/build.make" "Delta Applications/Tests/GFX-MultiCubeTex/CMakeFiles/GFX-MultiCubeTex.dir/build"
.PHONY : GFX-MultiCubeTex/fast

#=============================================================================
# Target rules for targets named GFX-MultiColor

# Build rule for target.
GFX-MultiColor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-MultiColor
.PHONY : GFX-MultiColor

# fast build rule for target.
GFX-MultiColor/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-MultiColor/CMakeFiles/GFX-MultiColor.dir/build.make" "Delta Applications/Tests/GFX-MultiColor/CMakeFiles/GFX-MultiColor.dir/build"
.PHONY : GFX-MultiColor/fast

#=============================================================================
# Target rules for targets named GFX-CubeMapTex

# Build rule for target.
GFX-CubeMapTex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-CubeMapTex
.PHONY : GFX-CubeMapTex

# fast build rule for target.
GFX-CubeMapTex/fast:
	$(MAKE) -f "Delta Applications/Tests/GFX-CubeMapTex/CMakeFiles/GFX-CubeMapTex.dir/build.make" "Delta Applications/Tests/GFX-CubeMapTex/CMakeFiles/GFX-CubeMapTex.dir/build"
.PHONY : GFX-CubeMapTex/fast

#=============================================================================
# Target rules for targets named CORE-GTest-ConfigFile

# Build rule for target.
CORE-GTest-ConfigFile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-ConfigFile
.PHONY : CORE-GTest-ConfigFile

# fast build rule for target.
CORE-GTest-ConfigFile/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-ConfigFile.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-ConfigFile.dir/build"
.PHONY : CORE-GTest-ConfigFile/fast

#=============================================================================
# Target rules for targets named CORE-GTest-ErrorCatch

# Build rule for target.
CORE-GTest-ErrorCatch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-ErrorCatch
.PHONY : CORE-GTest-ErrorCatch

# fast build rule for target.
CORE-GTest-ErrorCatch/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-ErrorCatch.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-ErrorCatch.dir/build"
.PHONY : CORE-GTest-ErrorCatch/fast

#=============================================================================
# Target rules for targets named CORE-GTest-IntrusiveLink

# Build rule for target.
CORE-GTest-IntrusiveLink: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-IntrusiveLink
.PHONY : CORE-GTest-IntrusiveLink

# fast build rule for target.
CORE-GTest-IntrusiveLink/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-IntrusiveLink.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-IntrusiveLink.dir/build"
.PHONY : CORE-GTest-IntrusiveLink/fast

#=============================================================================
# Target rules for targets named CORE-GTest-MessageClient

# Build rule for target.
CORE-GTest-MessageClient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-MessageClient
.PHONY : CORE-GTest-MessageClient

# fast build rule for target.
CORE-GTest-MessageClient/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-MessageClient.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-MessageClient.dir/build"
.PHONY : CORE-GTest-MessageClient/fast

#=============================================================================
# Target rules for targets named CORE-GTest-MessageServer

# Build rule for target.
CORE-GTest-MessageServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-MessageServer
.PHONY : CORE-GTest-MessageServer

# fast build rule for target.
CORE-GTest-MessageServer/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-MessageServer.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-MessageServer.dir/build"
.PHONY : CORE-GTest-MessageServer/fast

#=============================================================================
# Target rules for targets named CORE-GTest-Wfile

# Build rule for target.
CORE-GTest-Wfile: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-Wfile
.PHONY : CORE-GTest-Wfile

# fast build rule for target.
CORE-GTest-Wfile/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-Wfile.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-Wfile.dir/build"
.PHONY : CORE-GTest-Wfile/fast

#=============================================================================
# Target rules for targets named CORE-GTest-WorldObject

# Build rule for target.
CORE-GTest-WorldObject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CORE-GTest-WorldObject
.PHONY : CORE-GTest-WorldObject

# fast build rule for target.
CORE-GTest-WorldObject/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-WorldObject.dir/build.make" "Delta Applications/GTests/Framework/Core/CMakeFiles/CORE-GTest-WorldObject.dir/build"
.PHONY : CORE-GTest-WorldObject/fast

#=============================================================================
# Target rules for targets named GFX-GTest

# Build rule for target.
GFX-GTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GFX-GTest
.PHONY : GFX-GTest

# fast build rule for target.
GFX-GTest/fast:
	$(MAKE) -f "Delta Applications/GTests/Framework/Gfx/CMakeFiles/GFX-GTest.dir/build.make" "Delta Applications/GTests/Framework/Gfx/CMakeFiles/GFX-GTest.dir/build"
.PHONY : GFX-GTest/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Core"
	@echo "... Gfx"
	@echo "... Audio"
	@echo "... Network"
	@echo "... CORE-ConfigReadWriteTest"
	@echo "... CORE-MessagingTest"
	@echo "... GFX-CameraMoveTest"
	@echo "... GFX-TextureTest"
	@echo "... GfxRenderExample"
	@echo "... GfxViewportTest"
	@echo "... SDL-InputTest"
	@echo "... GFX-Cube"
	@echo "... GFX-MultiCube"
	@echo "... GFX-MultiCubeTex"
	@echo "... GFX-MultiColor"
	@echo "... GFX-CubeMapTex"
	@echo "... CORE-GTest-ConfigFile"
	@echo "... CORE-GTest-ErrorCatch"
	@echo "... CORE-GTest-IntrusiveLink"
	@echo "... CORE-GTest-MessageClient"
	@echo "... CORE-GTest-MessageServer"
	@echo "... CORE-GTest-Wfile"
	@echo "... CORE-GTest-WorldObject"
	@echo "... GFX-GTest"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

